[package]
name = "teloxide-macros"
version = "0.6.3"
description = "The teloxide's procedural macros"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.19"
syn = { version = "1.0.13",  features = ["full"] }
heck = "0.4.0"

[dev-dependencies]
# XXX: Do not enable `macros` feature
teloxide = { git = "https://github.com/teloxide/teloxide.git", rev = "b5e237a8a22f9f987b6e4245b9b6c3ca1f804c19" }
