[package]
name = "teloxide-core"
version = "0.1.0"
edition = "2018"
authors = [
    "Temirkhan Myrzamadi <hirrolot@gmail.com>",
    "Waffle Lapkin <waffle.lapkin@gmail.com>",
    "p0lunin <dmytro.polunin@gmail.com>",
    "Mishko torop'izhko",
    "Mr-Andersen",
    "Sergey Levitin <selevit@gmail.com>",
    "Rustem B. <bakirov.com@yandex.ru>",
    "Alexey Fedechkin <aleksey-fedechkin@rambler.ru>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["fs", "stream"] }
tokio-util = "0.3.1"
pin-project = "0.4.23"
bytes = "0.5.5"
async-trait = "0.1.36"
reqwest = { version = "0.10.6", features = ["json", "stream"] }

serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with_macros = "1.1.0"
uuid = { version = "0.8.1", features = ["v4"] } # for attaching input files
 
derive_more = "0.99.9"
mime = "0.3.16"
thiserror = "1.0.20"
once_cell = "1.4.0"
never = "0.1.0"

# FIXME(waffle): use crates.io once published
vecrem = { git = "https://github.com/WaffleLapkin/vecrem", rev = "6b9b6f42342df8b75548c6ed387072ff235429b1" }

[features]
default = []

# Features which require nightly compiler.
#
# Currently the only used compiler feature is feature(type_alias_impl_trait)
# which allow implementing `Future`s without boxing.
nightly = []

# Throttling bot adaptor
throttle = []

# CacheMe bot adaptor
cache_me = []

# AutoSend bot adaptor
auto_send = []

full = ["throttle", "cache_me", "auto_send"]

[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
