[package]
name = "teloxide-core"
version = "0.1.0"
edition = "2018"
authors = [
    "Temirkhan Myrzamadi <hirrolot@gmail.com>",
    "Waffle Lapkin <waffle.lapkin@gmail.com>",
    "p0lunin <dmytro.polunin@gmail.com>",
    "Mishko torop'izhko",
    "Mr-Andersen",
    "Sergey Levitin <selevit@gmail.com>",
    "Rustem B. <bakirov.com@yandex.ru>",
    "Alexey Fedechkin <aleksey-fedechkin@rambler.ru>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["fs", "stream"] }
tokio-util = "0.3.1"
bytes = "0.5.5"
async-trait = "0.1.36"
reqwest = { version = "0.10.6", features = ["json", "stream"] }

serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with_macros = "1.1.0"

derive_more = "0.99.9"
mime = "0.3.16"
thiserror = "1.0.20"

[features]
# features those require nightly compiler
nightly = []

[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
